In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
product = pd.read_csv(r'D:\2nd_project\Retails Analytics\products.csv')

In [4]:
product.head(50)

,product_id,product_name,category,brand,cost_price,unit_price,margin_pct
0,P0000,BrandA Shoulder,Electronics,BrandC,52.75,64.65,18.41
1,P0001,BrandA Responsibility,Electronics,BrandD,11.20,13.26,15.54
2,P0002,BrandB Small,Electronics,BrandB,144.62,250.37,42.24
3,P0003,BrandD Continue,Apparel,BrandD,119.91,219.25,45.31
4,P0004,BrandA Indeed,Apparel,BrandD,71.35,88.47,19.35
5,P0005,BrandC Cut,Electronics,BrandA,79.09,112.55,29.73
6,P0006,BrandC Air,Home & Kitchen,BrandA,147.30,233.12,36.81
7,P0007,BrandD State,Electronics,BrandC,166.73,276.22,39.64
8,P0008,BrandC Growth,Apparel,BrandA,13.94,18.19,23.36
9,P0009,BrandC Keep,Electronics,BrandB,173.96,250.87,30.66
10,P0010,BrandD Reveal,Home & Kitchen,BrandB,77.19,99.46,22.39
11,P0011,BrandC Laugh,Electronics,BrandB,109.16,144.13,24.26
12,P0012,BrandD Cell,Personal Care,BrandC,197.96,331.78,40.33
13,P0013,BrandB Seat,Home & Kitchen,BrandA,49.66,56.06,11.42
14,P0014,BrandC Argue,Personal Care,BrandC,17.91,34.42,47.97
15,P0015,BrandC Peace,Apparel,BrandD,82.15,157.98,48.00
16,P0016,BrandD Crime,Apparel,BrandC,32.23,57.06,43.52
17,P0017,BrandC Firm,Personal Care,BrandD,75.59,151.00,49.94
18,P0018,BrandB Management,Personal Care,BrandA,152.38,285.71,46.67
19,P0019,BrandB Left,Apparel,BrandD,121.30,175.44,30.86
20,P0020,BrandD House,Home & Kitchen,BrandA,137.66,165.62,16.88
21,P0021,BrandC Shake,Home & Kitchen,BrandA,62.23,77.31,19.51
22,P0022,BrandA Much,Home & Kitchen,BrandB,104.00,124.36,16.37
23,P0023,BrandC Believe,Apparel,NaN,77.91,97.03,19.71
24,P0024,BrandA Black,Home & Kitchen,BrandD,8.80,17.04,48.36
25,P0025,BrandC Resource,Apparel,BrandA,51.97,83.70,37.91
26,P0026,BrandA Fund,Electronics,BrandD,164.12,324.99,49.50
27,P0027,BrandB Probably,Apparel,BrandD,189.64,236.79,19.91
28,P0028,BrandD Degree,Apparel,BrandB,144.03,210.15,31.46
29,P0029,BrandC Stuff,Personal Care,BrandD,28.60,37.24,23.20
30,P0030,BrandC War,Electronics,BrandB,119.75,132.50,9.62
31,P0031,BrandA Responsibility,Apparel,BrandA,181.56,340.18,46.63
32,P0032,BrandA Role,Apparel,BrandC,135.45,175.11,22.65
33,P0033,BrandB Training,Personal Care,BrandB,158.00,288.63,45.26
34,P0034,BrandB Draw,Electronics,BrandA,133.50,189.42,29.52
35,P0035,BrandD Sure,Personal Care,BrandA,136.31,270.68,49.64
36,P0036,BrandA Beautiful,Electronics,BrandD,147.00,267.62,45.07
37,P0037,BrandA One,Apparel,BrandB,42.09,63.29,33.50
38,P0038,BrandD The,Apparel,BrandC,95.21,179.66,47.01
39,P0039,BrandA Professor,Personal Care,BrandA,14.86,29.71,49.98
40,P0040,BrandA Identify,Electronics,BrandB,37.43,57.53,34.94
41,P0041,BrandB Prevent,Personal Care,BrandA,37.10,40.88,9.25
42,P0042,BrandD Outside,Home & Kitchen,BrandD,60.62,104.69,42.10
43,P0043,BrandD Who,Apparel,NaN,62.86,123.95,49.29
44,P0044,BrandA Argue,Home & Kitchen,NaN,14.78,22.60,34.60
45,P0045,BrandB Tend,Electronics,BrandA,171.01,198.66,13.92
46,P0046,BrandA Usually,Apparel,BrandD,28.38,53.96,47.41
47,P0047,BrandB Son,Electronics,BrandA,86.75,141.00,38.48
48,P0048,BrandC Carry,Home & Kitchen,BrandB,135.60,187.50,27.68
49,P0049,BrandC Bit,Personal Care,NaN,135.98,186.29,27.01

In [6]:
null_percentage = (product.isnull().sum() / len(product)) * 100
print(null_percentage)

product_id      0.000000
product_name    0.000000
category        0.000000
brand           4.901961
cost_price      0.000000
unit_price      0.000000
margin_pct      0.000000
dtype: float64

In [7]:
product = product.dropna(subset=['brand'])

In [8]:
product.head(50)

,product_id,product_name,category,brand,cost_price,unit_price,margin_pct
0,P0000,BrandA Shoulder,Electronics,BrandC,52.75,64.65,18.41
1,P0001,BrandA Responsibility,Electronics,BrandD,11.20,13.26,15.54
2,P0002,BrandB Small,Electronics,BrandB,144.62,250.37,42.24
3,P0003,BrandD Continue,Apparel,BrandD,119.91,219.25,45.31
4,P0004,BrandA Indeed,Apparel,BrandD,71.35,88.47,19.35
5,P0005,BrandC Cut,Electronics,BrandA,79.09,112.55,29.73
6,P0006,BrandC Air,Home & Kitchen,BrandA,147.30,233.12,36.81
7,P0007,BrandD State,Electronics,BrandC,166.73,276.22,39.64
8,P0008,BrandC Growth,Apparel,BrandA,13.94,18.19,23.36
9,P0009,BrandC Keep,Electronics,BrandB,173.96,250.87,30.66
10,P0010,BrandD Reveal,Home & Kitchen,BrandB,77.19,99.46,22.39
11,P0011,BrandC Laugh,Electronics,BrandB,109.16,144.13,24.26
12,P0012,BrandD Cell,Personal Care,BrandC,197.96,331.78,40.33
13,P0013,BrandB Seat,Home & Kitchen,BrandA,49.66,56.06,11.42
14,P0014,BrandC Argue,Personal Care,BrandC,17.91,34.42,47.97
15,P0015,BrandC Peace,Apparel,BrandD,82.15,157.98,48.00
16,P0016,BrandD Crime,Apparel,BrandC,32.23,57.06,43.52
17,P0017,BrandC Firm,Personal Care,BrandD,75.59,151.00,49.94
18,P0018,BrandB Management,Personal Care,BrandA,152.38,285.71,46.67
19,P0019,BrandB Left,Apparel,BrandD,121.30,175.44,30.86
20,P0020,BrandD House,Home & Kitchen,BrandA,137.66,165.62,16.88
21,P0021,BrandC Shake,Home & Kitchen,BrandA,62.23,77.31,19.51
22,P0022,BrandA Much,Home & Kitchen,BrandB,104.00,124.36,16.37
24,P0024,BrandA Black,Home & Kitchen,BrandD,8.80,17.04,48.36
25,P0025,BrandC Resource,Apparel,BrandA,51.97,83.70,37.91
26,P0026,BrandA Fund,Electronics,BrandD,164.12,324.99,49.50
27,P0027,BrandB Probably,Apparel,BrandD,189.64,236.79,19.91
28,P0028,BrandD Degree,Apparel,BrandB,144.03,210.15,31.46
29,P0029,BrandC Stuff,Personal Care,BrandD,28.60,37.24,23.20
30,P0030,BrandC War,Electronics,BrandB,119.75,132.50,9.62
31,P0031,BrandA Responsibility,Apparel,BrandA,181.56,340.18,46.63
32,P0032,BrandA Role,Apparel,BrandC,135.45,175.11,22.65
33,P0033,BrandB Training,Personal Care,BrandB,158.00,288.63,45.26
34,P0034,BrandB Draw,Electronics,BrandA,133.50,189.42,29.52
35,P0035,BrandD Sure,Personal Care,BrandA,136.31,270.68,49.64
36,P0036,BrandA Beautiful,Electronics,BrandD,147.00,267.62,45.07
37,P0037,BrandA One,Apparel,BrandB,42.09,63.29,33.50
38,P0038,BrandD The,Apparel,BrandC,95.21,179.66,47.01
39,P0039,BrandA Professor,Personal Care,BrandA,14.86,29.71,49.98
40,P0040,BrandA Identify,Electronics,BrandB,37.43,57.53,34.94
41,P0041,BrandB Prevent,Personal Care,BrandA,37.10,40.88,9.25
42,P0042,BrandD Outside,Home & Kitchen,BrandD,60.62,104.69,42.10
45,P0045,BrandB Tend,Electronics,BrandA,171.01,198.66,13.92
46,P0046,BrandA Usually,Apparel,BrandD,28.38,53.96,47.41
47,P0047,BrandB Son,Electronics,BrandA,86.75,141.00,38.48
48,P0048,BrandC Carry,Home & Kitchen,BrandB,135.60,187.50,27.68
50,P0050,BrandC Marriage,Electronics,BrandA,94.37,188.61,49.97
51,P0051,BrandA Table,Electronics,BrandB,103.65,126.37,17.98
52,P0052,BrandC Agency,Electronics,BrandB,77.06,95.71,19.49
53,P0053,BrandC Decision,Electronics,BrandC,186.69,222.76,16.19

In [12]:
product.duplicated(subset=['product_id']).sum()

np.int64(0)

In [11]:
product= product.drop_duplicates(subset=['product_id'])

In [13]:
product.dtypes

product_id       object
product_name     object
category         object
brand            object
cost_price      float64
unit_price      float64
margin_pct      float64
dtype: object

In [15]:
product[['unit_price','cost_price']].dtypes

unit_price    float64
cost_price    float64
dtype: object

In [23]:
product['Price_Tier'] = pd.cut(
    product['unit_price'],
    bins=[0, 100, 200, float('inf')],
    labels=['Budget', 'Mid-Range', 'Premium']
)

In [24]:
product.head(50)

,product_id,product_name,category,brand,cost_price,unit_price,margin_pct,Price_Tier
0,P0000,BrandA Shoulder,Electronics,BrandC,52.75,64.65,18.41,Budget
1,P0001,BrandA Responsibility,Electronics,BrandD,11.20,13.26,15.54,Budget
2,P0002,BrandB Small,Electronics,BrandB,144.62,250.37,42.24,Premium
3,P0003,BrandD Continue,Apparel,BrandD,119.91,219.25,45.31,Premium
4,P0004,BrandA Indeed,Apparel,BrandD,71.35,88.47,19.35,Budget
5,P0005,BrandC Cut,Electronics,BrandA,79.09,112.55,29.73,Mid-Range
6,P0006,BrandC Air,Home & Kitchen,BrandA,147.30,233.12,36.81,Premium
7,P0007,BrandD State,Electronics,BrandC,166.73,276.22,39.64,Premium
8,P0008,BrandC Growth,Apparel,BrandA,13.94,18.19,23.36,Budget
9,P0009,BrandC Keep,Electronics,BrandB,173.96,250.87,30.66,Premium
10,P0010,BrandD Reveal,Home & Kitchen,BrandB,77.19,99.46,22.39,Budget
11,P0011,BrandC Laugh,Electronics,BrandB,109.16,144.13,24.26,Mid-Range
12,P0012,BrandD Cell,Personal Care,BrandC,197.96,331.78,40.33,Premium
13,P0013,BrandB Seat,Home & Kitchen,BrandA,49.66,56.06,11.42,Budget
14,P0014,BrandC Argue,Personal Care,BrandC,17.91,34.42,47.97,Budget
15,P0015,BrandC Peace,Apparel,BrandD,82.15,157.98,48.00,Mid-Range
16,P0016,BrandD Crime,Apparel,BrandC,32.23,57.06,43.52,Budget
17,P0017,BrandC Firm,Personal Care,BrandD,75.59,151.00,49.94,Mid-Range
18,P0018,BrandB Management,Personal Care,BrandA,152.38,285.71,46.67,Premium
19,P0019,BrandB Left,Apparel,BrandD,121.30,175.44,30.86,Mid-Range
20,P0020,BrandD House,Home & Kitchen,BrandA,137.66,165.62,16.88,Mid-Range
21,P0021,BrandC Shake,Home & Kitchen,BrandA,62.23,77.31,19.51,Budget
22,P0022,BrandA Much,Home & Kitchen,BrandB,104.00,124.36,16.37,Mid-Range
24,P0024,BrandA Black,Home & Kitchen,BrandD,8.80,17.04,48.36,Budget
25,P0025,BrandC Resource,Apparel,BrandA,51.97,83.70,37.91,Budget
26,P0026,BrandA Fund,Electronics,BrandD,164.12,324.99,49.50,Premium
27,P0027,BrandB Probably,Apparel,BrandD,189.64,236.79,19.91,Premium
28,P0028,BrandD Degree,Apparel,BrandB,144.03,210.15,31.46,Premium
29,P0029,BrandC Stuff,Personal Care,BrandD,28.60,37.24,23.20,Budget
30,P0030,BrandC War,Electronics,BrandB,119.75,132.50,9.62,Mid-Range
31,P0031,BrandA Responsibility,Apparel,BrandA,181.56,340.18,46.63,Premium
32,P0032,BrandA Role,Apparel,BrandC,135.45,175.11,22.65,Mid-Range
33,P0033,BrandB Training,Personal Care,BrandB,158.00,288.63,45.26,Premium
34,P0034,BrandB Draw,Electronics,BrandA,133.50,189.42,29.52,Mid-Range
35,P0035,BrandD Sure,Personal Care,BrandA,136.31,270.68,49.64,Premium
36,P0036,BrandA Beautiful,Electronics,BrandD,147.00,267.62,45.07,Premium
37,P0037,BrandA One,Apparel,BrandB,42.09,63.29,33.50,Budget
38,P0038,BrandD The,Apparel,BrandC,95.21,179.66,47.01,Mid-Range
39,P0039,BrandA Professor,Personal Care,BrandA,14.86,29.71,49.98,Budget
40,P0040,BrandA Identify,Electronics,BrandB,37.43,57.53,34.94,Budget
41,P0041,BrandB Prevent,Personal Care,BrandA,37.10,40.88,9.25,Budget
42,P0042,BrandD Outside,Home & Kitchen,BrandD,60.62,104.69,42.10,Mid-Range
45,P0045,BrandB Tend,Electronics,BrandA,171.01,198.66,13.92,Mid-Range
46,P0046,BrandA Usually,Apparel,BrandD,28.38,53.96,47.41,Budget
47,P0047,BrandB Son,Electronics,BrandA,86.75,141.00,38.48,Mid-Range
48,P0048,BrandC Carry,Home & Kitchen,BrandB,135.60,187.50,27.68,Mid-Range
50,P0050,BrandC Marriage,Electronics,BrandA,94.37,188.61,49.97,Mid-Range
51,P0051,BrandA Table,Electronics,BrandB,103.65,126.37,17.98,Mid-Range
52,P0052,BrandC Agency,Electronics,BrandB,77.06,95.71,19.49,Budget
53,P0053,BrandC Decision,Electronics,BrandC,186.69,222.76,16.19,Premium

In [25]:
product.to_csv('sql_product.csv', index=False)
print("Product data cleaned with age_group!")

Product data cleaned with age_group!