In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
sales = pd.read_csv(r'D:\2nd_project\Retails Analytics\salesdata.csv')

In [4]:
sales

,order_id,order_date,customer_id,product_id,store_id,sales_channel,quantity,unit_price,discount_pct,total_amount
0,O00000,31-01-2025,C0125,P1086,NaN,Online,2,80.63,0.05,153.20
1,O00001,29-09-2025,C0633,P0973,S042,In-Store,20,209.16,0.05,3974.00
2,O00002,29-08-2024,C0653,P0659,NaN,Online,2,218.60,0.10,393.48
3,O00003,13-05-2025,C0753,P0666,S014,In-Store,1,78.53,0.20,62.82
4,O00004,22-07-2025,C0627,P0166,S017,In-Store,1,344.93,0.20,275.94
...,...,...,...,...,...,...,...,...,...,...
3055,O02044,26-09-2025,C0580,P0886,S024,In-Store,2,82.92,0.00,165.84
3056,O02352,16-11-2024,C0632,P0091,S034,In-Store,1,27.29,0.10,24.56
3057,O02014,25-06-2024,C0127,P0296,NaN,Online,3,34.89,0.00,104.67
3058,O01371,12-02-2025,C0741,P1056,NaN,Online,1,57.51,0.05,54.63
3059,O00797,27-03-2025,C0479,P0659,NaN,Online,10,218.60,0.10,1967.40

In [5]:
sales['order_id'].isnull().sum()

np.int64(0)

In [6]:
sales['store_id'] = sales['store_id'].fillna('ONLINE')

In [7]:
sales.head(50)

,order_id,order_date,customer_id,product_id,store_id,sales_channel,quantity,unit_price,discount_pct,total_amount
0,O00000,31-01-2025,C0125,P1086,ONLINE,Online,2,80.63,0.05,153.20
1,O00001,29-09-2025,C0633,P0973,S042,In-Store,20,209.16,0.05,3974.00
2,O00002,29-08-2024,C0653,P0659,ONLINE,Online,2,218.60,0.10,393.48
3,O00003,13-05-2025,C0753,P0666,S014,In-Store,1,78.53,0.20,62.82
4,O00004,22-07-2025,C0627,P0166,S017,In-Store,1,344.93,0.20,275.94
5,O00005,16-12-2025,C0716,P0205,S018,In-Store,1,14.31,0.05,13.59
6,O00006,25-09-2024,C0532,P1171,S045,In-Store,2,230.62,0.00,461.24
7,O00007,27-09-2024,C0515,P0178,S043,In-Store,2,129.07,0.20,206.51
8,O00008,01-03-2025,C0456,P0236,S034,In-Store,2,196.93,0.05,374.17
9,O00009,02-12-2024,C0174,P0183,ONLINE,Online,3,304.66,0.00,913.98
10,O00010,03-05-2024,C0334,P0785,S014,In-Store,1,57.39,0.10,51.65
11,O00011,12-04-2025,C0686,P0252,S059,In-Store,2,231.15,0.20,369.84
12,O00012,13-11-2025,C0708,P0681,S059,In-Store,1,342.55,0.00,342.55
13,O00013,05-10-2025,C0386,P0781,S050,In-Store,1,153.30,0.20,122.64
14,O00014,18-11-2025,C0228,P0530,ONLINE,Online,2,274.32,0.00,548.64
15,O00015,06-05-2025,C0348,P0528,S047,In-Store,2,102.08,0.00,204.16
16,O00016,16-07-2024,C0130,P0641,S036,In-Store,1,240.92,0.00,240.92
17,O00017,19-01-2025,C0604,P1096,ONLINE,Online,1,214.66,0.20,171.73
18,O00018,05-03-2025,C0327,P0747,S059,In-Store,1,127.24,0.05,120.88
19,O00019,28-04-2024,C0616,P0255,ONLINE,Online,10,21.15,0.20,169.20
20,O00020,15-03-2025,C0471,P0647,ONLINE,Online,2,139.35,0.10,250.83
21,O00021,27-11-2024,C0511,P0933,ONLINE,Online,2,25.25,0.10,45.45
22,O00022,28-06-2025,C0681,P0070,S019,In-Store,2,235.00,0.00,470.00
23,O00023,10-10-2025,C0723,P1175,S053,In-Store,2,26.47,0.05,50.29
24,O00024,16-07-2025,C0721,P0771,ONLINE,Online,2,155.11,0.10,279.20
25,O00025,19-05-2025,C0733,P0431,S059,In-Store,1,39.30,0.05,37.33
26,O00026,07-03-2025,C0053,P0366,S046,In-Store,2,230.23,0.20,368.37
27,O00027,03-04-2025,C0675,P0326,S035,In-Store,2,134.39,0.20,215.02
28,O00028,17-08-2024,C0694,P0969,S048,In-Store,2,171.98,0.20,275.17
29,O00029,12-07-2025,C0540,P0579,ONLINE,Online,1,137.64,0.05,130.76
30,O00030,21-10-2025,C0561,P0806,ONLINE,Online,1,38.24,0.10,34.42
31,O00031,18-02-2025,C0594,P0110,S045,In-Store,3,280.19,0.10,756.51
32,O00032,27-01-2025,C0167,P1182,ONLINE,Online,1,275.08,0.20,220.06
33,O00033,19-06-2025,C0148,P0429,ONLINE,Online,1,257.83,0.05,244.94
34,O00034,04-06-2025,C0009,P0741,S036,In-Store,2,25.86,0.00,51.72
35,O00035,14-09-2024,C0151,P0771,S027,In-Store,1,155.11,0.05,147.35
36,O00036,14-12-2024,C0098,P0728,S011,In-Store,3,242.37,0.00,727.11
37,O00037,14-06-2025,C0527,P0693,S009,In-Store,2,147.47,0.20,235.95
38,O00038,26-11-2025,C0121,P0493,S019,In-Store,2,178.11,0.05,338.41
39,O00039,18-08-2025,C0384,P0183,S055,In-Store,1,304.66,0.20,243.73
40,O00040,19-04-2024,C0668,P0911,S007,In-Store,3,298.36,0.00,895.08
41,O00041,30-12-2024,C0500,P1043,ONLINE,Online,2,321.82,0.20,514.91
42,O00042,13-01-2025,C0763,P0193,S011,In-Store,1,62.96,0.20,50.37
43,O00043,28-05-2025,C0660,P0888,ONLINE,Online,2,99.91,0.05,189.83
44,O00044,09-12-2024,C0065,P1100,ONLINE,Online,1,74.54,0.00,74.54
45,O00045,10-05-2025,C0549,P1085,S033,In-Store,2,42.67,0.00,85.34
46,O00046,09-02-2025,C0212,P0240,ONLINE,Online,10,85.49,0.05,812.20
47,O00047,01-08-2024,C0457,P0643,ONLINE,Online,1,252.43,0.05,239.81
48,O00048,29-08-2025,C0668,P0330,ONLINE,Online,1,355.55,0.10,320.00
49,O00049,02-05-2025,C0035,P0173,S032,In-Store,3,209.18,0.10,564.79

In [36]:
sales["order_id"].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2995    False
2996    False
2997    False
2998    False
2999    False
Name: order_id, Length: 2994, dtype: bool

In [35]:
sales = sales.drop_duplicates(subset=["order_id"])

In [8]:
sales['order_date'] = pd.to_datetime(
    sales['order_date'],
    dayfirst=True,
    errors='coerce'
)

In [9]:
sales = sales.dropna(subset=['order_date'])

In [10]:
sales['order_date'] = sales['order_date'].dt.strftime('%Y-%m-%d')

C:\Users\affan\AppData\Local\Temp\ipykernel_5340\274044855.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales['order_date'] = sales['order_date'].dt.strftime('%Y-%m-%d')

In [11]:
sales

,order_id,order_date,customer_id,product_id,store_id,sales_channel,quantity,unit_price,discount_pct,total_amount
0,O00000,2025-01-31,C0125,P1086,ONLINE,Online,2,80.63,0.05,153.20
1,O00001,2025-09-29,C0633,P0973,S042,In-Store,20,209.16,0.05,3974.00
2,O00002,2024-08-29,C0653,P0659,ONLINE,Online,2,218.60,0.10,393.48
3,O00003,2025-05-13,C0753,P0666,S014,In-Store,1,78.53,0.20,62.82
4,O00004,2025-07-22,C0627,P0166,S017,In-Store,1,344.93,0.20,275.94
...,...,...,...,...,...,...,...,...,...,...
3055,O02044,2025-09-26,C0580,P0886,S024,In-Store,2,82.92,0.00,165.84
3056,O02352,2024-11-16,C0632,P0091,S034,In-Store,1,27.29,0.10,24.56
3057,O02014,2024-06-25,C0127,P0296,ONLINE,Online,3,34.89,0.00,104.67
3058,O01371,2025-02-12,C0741,P1056,ONLINE,Online,1,57.51,0.05,54.63
3059,O00797,2025-03-27,C0479,P0659,ONLINE,Online,10,218.60,0.10,1967.40

In [12]:
products = pd.read_csv(r'D:\2nd_project\Retails Analytics\products.csv')
print(products.head())

  product_id           product_name     category   brand  cost_price  \
0      P0000        BrandA Shoulder  Electronics  BrandC       52.75
1      P0001  BrandA Responsibility  Electronics  BrandD       11.20
2      P0002           BrandB Small  Electronics  BrandB      144.62
3      P0003        BrandD Continue      Apparel  BrandD      119.91
4      P0004          BrandA Indeed      Apparel  BrandD       71.35

   unit_price  margin_pct
0       64.65       18.41
1       13.26       15.54
2      250.37       42.24
3      219.25       45.31
4       88.47       19.35

In [13]:
merge = sales.merge(
    products[['product_id', 'cost_price']],
    on='product_id',
    how='left'
)

In [14]:
print(merge.head())

  order_id  order_date customer_id product_id store_id sales_channel  \
0   O00000  2025-01-31       C0125      P1086   ONLINE        Online
1   O00001  2025-09-29       C0633      P0973     S042      In-Store
2   O00002  2024-08-29       C0653      P0659   ONLINE        Online
3   O00003  2025-05-13       C0753      P0666     S014      In-Store
4   O00004  2025-07-22       C0627      P0166     S017      In-Store

   quantity  unit_price  discount_pct  total_amount  cost_price
0         2       80.63          0.05        153.20       69.87
1        20      209.16          0.05       3974.00      120.11
2         2      218.60          0.10        393.48      173.17
3         1       78.53          0.20         62.82       65.86
4         1      344.93          0.20        275.94      174.83

In [15]:
merge['Gross_Profit'] = merge['total_amount'] - (merge['cost_price'] * merge['quantity'])

In [16]:
print(merge[['product_id', 'total_amount', 'cost_price', 'quantity', 'Gross_Profit']].head())

  product_id  total_amount  cost_price  quantity  Gross_Profit
0      P1086        153.20       69.87         2         13.46
1      P0973       3974.00      120.11        20       1571.80
2      P0659        393.48      173.17         2         47.14
3      P0666         62.82       65.86         1         -3.04
4      P0166        275.94      174.83         1        101.11

In [17]:
merge['cost_price'] = merge['cost_price'].fillna(0)

In [18]:
merge['Profit_%'] = (merge['Gross_Profit'] / merge['total_amount']) * 100

In [19]:
merge

,order_id,order_date,customer_id,product_id,store_id,sales_channel,quantity,unit_price,discount_pct,total_amount,cost_price,Gross_Profit,Profit_%
0,O00000,2025-01-31,C0125,P1086,ONLINE,Online,2,80.63,0.05,153.20,69.87,13.46,8.785901
1,O00001,2025-09-29,C0633,P0973,S042,In-Store,20,209.16,0.05,3974.00,120.11,1571.80,39.552089
2,O00002,2024-08-29,C0653,P0659,ONLINE,Online,2,218.60,0.10,393.48,173.17,47.14,11.980279
3,O00003,2025-05-13,C0753,P0666,S014,In-Store,1,78.53,0.20,62.82,65.86,-3.04,-4.839223
4,O00004,2025-07-22,C0627,P0166,S017,In-Store,1,344.93,0.20,275.94,174.83,101.11,36.642024
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3173,O02044,2025-09-26,C0580,P0886,S024,In-Store,2,82.92,0.00,165.84,53.50,58.84,35.479981
3174,O02352,2024-11-16,C0632,P0091,S034,In-Store,1,27.29,0.10,24.56,20.11,4.45,18.118893
3175,O02014,2024-06-25,C0127,P0296,ONLINE,Online,3,34.89,0.00,104.67,25.01,29.64,28.317570
3176,O01371,2025-02-12,C0741,P1056,ONLINE,Online,1,57.51,0.05,54.63,32.71,21.92,40.124474
3177,O00797,2025-03-27,C0479,P0659,ONLINE,Online,10,218.60,0.10,1967.40,173.17,235.70,11.980279

In [20]:
returns = pd.read_csv(r'D:\2nd_project\Retails Analytics\returns.csv')

In [21]:
sales['Is_Returned'] = sales['order_id'].isin(returns['order_id']).astype(int)

C:\Users\affan\AppData\Local\Temp\ipykernel_5340\1672541507.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales['Is_Returned'] = sales['order_id'].isin(returns['order_id']).astype(int)

In [22]:
return_rate = sales['Is_Returned'].mean() * 100
print("Return Rate:", return_rate, "%")

Return Rate: 6.448445171849428 %

In [23]:
return_rate = sales['Is_Returned'].mean() * 100
print("Return Rate:", return_rate, "%")

Return Rate: 6.448445171849428 %

In [24]:
store_return = sales.groupby('store_id')['Is_Returned'].mean() * 100
print(store_return)

store_id
ONLINE     6.066734
S000       3.030303
S001       5.405405
S002      14.705882
S003      13.333333
            ...
S055       5.555556
S056       0.000000
S057       6.250000
S058      11.111111
S059       9.302326
Name: Is_Returned, Length: 61, dtype: float64

In [25]:
sales.head(50)

,order_id,order_date,customer_id,product_id,store_id,sales_channel,quantity,unit_price,discount_pct,total_amount,Is_Returned
0,O00000,2025-01-31,C0125,P1086,ONLINE,Online,2,80.63,0.05,153.20,0
1,O00001,2025-09-29,C0633,P0973,S042,In-Store,20,209.16,0.05,3974.00,0
2,O00002,2024-08-29,C0653,P0659,ONLINE,Online,2,218.60,0.10,393.48,0
3,O00003,2025-05-13,C0753,P0666,S014,In-Store,1,78.53,0.20,62.82,0
4,O00004,2025-07-22,C0627,P0166,S017,In-Store,1,344.93,0.20,275.94,0
5,O00005,2025-12-16,C0716,P0205,S018,In-Store,1,14.31,0.05,13.59,0
6,O00006,2024-09-25,C0532,P1171,S045,In-Store,2,230.62,0.00,461.24,0
7,O00007,2024-09-27,C0515,P0178,S043,In-Store,2,129.07,0.20,206.51,0
8,O00008,2025-03-01,C0456,P0236,S034,In-Store,2,196.93,0.05,374.17,0
9,O00009,2024-12-02,C0174,P0183,ONLINE,Online,3,304.66,0.00,913.98,0
10,O00010,2024-05-03,C0334,P0785,S014,In-Store,1,57.39,0.10,51.65,0
11,O00011,2025-04-12,C0686,P0252,S059,In-Store,2,231.15,0.20,369.84,0
12,O00012,2025-11-13,C0708,P0681,S059,In-Store,1,342.55,0.00,342.55,0
13,O00013,2025-10-05,C0386,P0781,S050,In-Store,1,153.30,0.20,122.64,0
14,O00014,2025-11-18,C0228,P0530,ONLINE,Online,2,274.32,0.00,548.64,1
15,O00015,2025-05-06,C0348,P0528,S047,In-Store,2,102.08,0.00,204.16,0
16,O00016,2024-07-16,C0130,P0641,S036,In-Store,1,240.92,0.00,240.92,1
17,O00017,2025-01-19,C0604,P1096,ONLINE,Online,1,214.66,0.20,171.73,0
18,O00018,2025-03-05,C0327,P0747,S059,In-Store,1,127.24,0.05,120.88,0
19,O00019,2024-04-28,C0616,P0255,ONLINE,Online,10,21.15,0.20,169.20,0
20,O00020,2025-03-15,C0471,P0647,ONLINE,Online,2,139.35,0.10,250.83,1
21,O00021,2024-11-27,C0511,P0933,ONLINE,Online,2,25.25,0.10,45.45,0
22,O00022,2025-06-28,C0681,P0070,S019,In-Store,2,235.00,0.00,470.00,0
23,O00023,2025-10-10,C0723,P1175,S053,In-Store,2,26.47,0.05,50.29,0
24,O00024,2025-07-16,C0721,P0771,ONLINE,Online,2,155.11,0.10,279.20,0
25,O00025,2025-05-19,C0733,P0431,S059,In-Store,1,39.30,0.05,37.33,0
26,O00026,2025-03-07,C0053,P0366,S046,In-Store,2,230.23,0.20,368.37,0
27,O00027,2025-04-03,C0675,P0326,S035,In-Store,2,134.39,0.20,215.02,0
28,O00028,2024-08-17,C0694,P0969,S048,In-Store,2,171.98,0.20,275.17,0
29,O00029,2025-07-12,C0540,P0579,ONLINE,Online,1,137.64,0.05,130.76,0
30,O00030,2025-10-21,C0561,P0806,ONLINE,Online,1,38.24,0.10,34.42,0
31,O00031,2025-02-18,C0594,P0110,S045,In-Store,3,280.19,0.10,756.51,1
32,O00032,2025-01-27,C0167,P1182,ONLINE,Online,1,275.08,0.20,220.06,0
33,O00033,2025-06-19,C0148,P0429,ONLINE,Online,1,257.83,0.05,244.94,0
34,O00034,2025-06-04,C0009,P0741,S036,In-Store,2,25.86,0.00,51.72,0
35,O00035,2024-09-14,C0151,P0771,S027,In-Store,1,155.11,0.05,147.35,0
36,O00036,2024-12-14,C0098,P0728,S011,In-Store,3,242.37,0.00,727.11,0
37,O00037,2025-06-14,C0527,P0693,S009,In-Store,2,147.47,0.20,235.95,0
38,O00038,2025-11-26,C0121,P0493,S019,In-Store,2,178.11,0.05,338.41,0
39,O00039,2025-08-18,C0384,P0183,S055,In-Store,1,304.66,0.20,243.73,0
40,O00040,2024-04-19,C0668,P0911,S007,In-Store,3,298.36,0.00,895.08,0
41,O00041,2024-12-30,C0500,P1043,ONLINE,Online,2,321.82,0.20,514.91,0
42,O00042,2025-01-13,C0763,P0193,S011,In-Store,1,62.96,0.20,50.37,1
43,O00043,2025-05-28,C0660,P0888,ONLINE,Online,2,99.91,0.05,189.83,0
44,O00044,2024-12-09,C0065,P1100,ONLINE,Online,1,74.54,0.00,74.54,0
45,O00045,2025-05-10,C0549,P1085,S033,In-Store,2,42.67,0.00,85.34,0
46,O00046,2025-02-09,C0212,P0240,ONLINE,Online,10,85.49,0.05,812.20,1
47,O00047,2024-08-01,C0457,P0643,ONLINE,Online,1,252.43,0.05,239.81,0
48,O00048,2025-08-29,C0668,P0330,ONLINE,Online,1,355.55,0.10,320.00,0
49,O00049,2025-05-02,C0035,P0173,S032,In-Store,3,209.18,0.10,564.79,0

In [26]:
print(sales['order_date'].dtype)

object

In [27]:
sales['order_date'] = pd.to_datetime(
    sales['order_date'],
    errors='coerce'
)

C:\Users\affan\AppData\Local\Temp\ipykernel_5340\1655350145.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales['order_date'] = pd.to_datetime(

In [28]:
print(sales['order_date'].dtype)

datetime64[ns]

In [29]:
sales['Year'] = sales['order_date'].dt.year

C:\Users\affan\AppData\Local\Temp\ipykernel_5340\4004652406.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales['Year'] = sales['order_date'].dt.year

In [30]:
sales['Month_Name'] = sales['order_date'].dt.month_name()

C:\Users\affan\AppData\Local\Temp\ipykernel_5340\4005069172.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales['Month_Name'] = sales['order_date'].dt.month_name()

In [31]:
sales['Month_No'] = sales['order_date'].dt.month

C:\Users\affan\AppData\Local\Temp\ipykernel_5340\3666909150.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales['Month_No'] = sales['order_date'].dt.month

In [32]:
monthly_sales = sales.groupby(
    ['Year','Month_No','Month_Name']
)['total_amount'].sum().reset_index()

monthly_sales = monthly_sales.sort_values(['Year','Month_No'])

print(monthly_sales)

    Year  Month_No Month_Name  total_amount
0   2024         4      April      22339.94
1   2024         5        May      38218.45
2   2024         6       June      34880.73
3   2024         7       July      38832.57
4   2024         8     August      32139.32
5   2024         9  September      29853.40
6   2024        10    October      35869.18
7   2024        11   November      38230.39
8   2024        12   December      36658.48
9   2025         1    January      62568.94
10  2025         2   February      80647.27
11  2025         3      March      68625.55
12  2025         4      April      46764.32
13  2025         5        May      32744.08
14  2025         6       June      33100.61
15  2025         7       July      32125.29
16  2025         8     August      45554.62
17  2025         9  September      37805.29
18  2025        10    October      35135.28
19  2025        11   November      25501.58
20  2025        12   December      25081.01

In [33]:
sales

,order_id,order_date,customer_id,product_id,store_id,sales_channel,quantity,unit_price,discount_pct,total_amount,Is_Returned,Year,Month_Name,Month_No
0,O00000,2025-01-31,C0125,P1086,ONLINE,Online,2,80.63,0.05,153.20,0,2025,January,1
1,O00001,2025-09-29,C0633,P0973,S042,In-Store,20,209.16,0.05,3974.00,0,2025,September,9
2,O00002,2024-08-29,C0653,P0659,ONLINE,Online,2,218.60,0.10,393.48,0,2024,August,8
3,O00003,2025-05-13,C0753,P0666,S014,In-Store,1,78.53,0.20,62.82,0,2025,May,5
4,O00004,2025-07-22,C0627,P0166,S017,In-Store,1,344.93,0.20,275.94,0,2025,July,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3055,O02044,2025-09-26,C0580,P0886,S024,In-Store,2,82.92,0.00,165.84,0,2025,September,9
3056,O02352,2024-11-16,C0632,P0091,S034,In-Store,1,27.29,0.10,24.56,0,2024,November,11
3057,O02014,2024-06-25,C0127,P0296,ONLINE,Online,3,34.89,0.00,104.67,0,2024,June,6
3058,O01371,2025-02-12,C0741,P1056,ONLINE,Online,1,57.51,0.05,54.63,0,2025,February,2
3059,O00797,2025-03-27,C0479,P0659,ONLINE,Online,10,218.60,0.10,1967.40,0,2025,March,3

In [38]:
sales.to_csv('sql_sales.csv', index=False)
print("Customers data cleaned with age_group!")

Customers data cleaned with age_group!